const express=require("express")
const userSignUpController = require("../Controller/SignUp")
const cookieParser = require("cookie-parser")
const userLoginController = require("../Controller/Login")
const userDetailsController = require("../Controller/userDetailsController")
const authToken = require("../middleware/authToken")
const updateUser = require("../Controller/updateUser")
const userLogout = require("../Controller/userLogout")
const jobApplication = require("../Controller/jobApplicaton")
const viewJobDetailsController = require("../Controller/ViewJobDetailsController")
const viewJobandApply = require("../Controller/viewApplicationBigpage")
const resumeController = require("../Controller/resumeController")
const multer = require('../middleware/multer')
const viewAppliedJob = require("../Controller/JobseekerViewApplied")
const viewCandidateController = require("../Controller/viewCandidate")
const viewCreatedJob = require("../Controller/viewCreatedJob")
const editJobApplication = require("../Controller/editJobApplication")
const deleteJobApplication = require("../Controller/deleteJobApplication")
const resumeDownloadController = require("../Controller/resumeDownload")
const statusResumeController = require("../Controller/statusResume")


const router =express.Router()

router.use(cookieParser())


router.post("/signup",userSignUpController)
router.post("/login",userLoginController)
router.get("/user-details",authToken,userDetailsController)
router.post("/update-user",authToken,updateUser)
router.get("/user-logout",userLogout)
router.post("/job-application",authToken,jobApplication)
router.get("/all-job",authToken,viewJobDetailsController)
router.get("/apply-job",authToken,viewJobandApply)
router.post("/resume-upload",authToken,multer,resumeController)
router.get("/view-applied-job",authToken,viewAppliedJob)
router.get('/view-applied-candidates',authToken,viewCandidateController)
router.get("/viewCreatedJob",authToken,viewCreatedJob)
router.post("/editCreateJob",authToken,editJobApplication)
router.delete("/deleteJobApplication",authToken,deleteJobApplication)
router.get("/resumeDownload/:candidate_id",authToken,resumeDownloadController)
router.post("/resume-status",authToken,statusResumeController)

module.exports=router